pub mod configure;
pub mod doctor;
pub mod extensions;
pub mod gateway;
pub mod ide;
pub mod info;
pub mod mcp_manager;
pub mod mcp_registry;
pub mod models;
pub mod plugin;
pub mod project;
pub mod recipe;
pub mod review;
pub mod schedule;
pub mod session;
pub mod skills;
pub mod term;
#[cfg(feature = "tui")]
pub mod tui;
pub mod ui;
#[cfg(feature = "update")]
pub mod update;
