#!/usr/bin/env bash
# Appends a short prose section explaining what the merge conflicts are about.
#
# Feeds the model the conflict hunks only — never the diff. Upstream pours
# +22k lines into crates/goose alone over a release window, and none of it helps
# answer the one question a human has here: why do these two sides disagree.
#
# Prints nothing at all unless the whole thing succeeds, so a bad key or a dead
# model leaves the deterministic part of the PR body untouched.

set -uo pipefail

MODEL="${OPENROUTER_MODEL:-x-ai/grok-4.6}"
BUDGET=60000   # characters of hunks; the rest is dropped with a note

: "${OPENROUTER_API_KEY:?OPENROUTER_API_KEY is not set}"

# Sides get labelled here rather than left as raw markers. Measured on the real
# 1.46 conflicts: handed the markers, the model confidently swapped who wanted
# what in two cases out of three, always where one side was empty. Handed
# "[fork added] / [upstream added]", it got all ten blocks right.
relabel() {
    awk -v FN="$1" '
        /^<<<<<<< /  { n++; side=1; ours=""; theirs=""; next }
        /^\|\|\|\|\|\|\| / { side=3; next }          # diff3 base section, ignored
        /^=======$/  { if (side) { side=2; next } }
        /^>>>>>>> /  {
            side=0
            printf "--- %s, block %d ---\n[fork added]\n%s[upstream added]\n%s\n",
                   FN, n, (ours=="" ? "(nothing)\n" : ours),
                           (theirs=="" ? "(nothing)" : theirs)
            next
        }
        side==1 { ours = ours $0 "\n"; next }
        side==2 { theirs = theirs $0 "\n"; next }
    ' < "$2"
}

hunks=""
dropped=0
while read -r f; do
    [ -n "$f" ] || continue
    case "$(basename -- "$f")" in
        Cargo.lock|pnpm-lock.yaml|package-lock.json|yarn.lock|flake.lock) continue ;;
    esac
    piece="$(relabel "$f" "$f" 2>/dev/null)"
    [ -n "$piece" ] || continue
    piece="$piece
"
    if [ $(( ${#hunks} + ${#piece} )) -gt "$BUDGET" ]; then
        dropped=$((dropped + 1))
        continue
    fi
    hunks+="$piece"
done < <(git status --porcelain | awk '$1 == "UU" { print $2 }')

[ -n "$hunks" ] || exit 0

read -r -d '' PROMPT <<'PROMPT_END' || true
Below are git conflicts from merging a fork with its upstream. The sides are
already labelled for you.

Write one line per block, in the form "- `path` (block N) — ...", saying what
each side wants and why they collided. English, list only, no preamble and no
conclusion. If a block does not reveal the intent, say so.
PROMPT_END

# Reasoning only gets in the way here — this wants a list, not deliberation. But
# there is no single policy: nvidia/nemotron-3.5-lightning with reasoning on
# burns 7000 tokens and returns content: null, while x-ai/grok-4.6 answers any
# attempt to turn it off with 400 "Reasoning is mandatory for this endpoint".
# The model comes from a repository variable, so the choice has to be made at
# call time: ask for it off, and take no for an answer.
payload="$(jq -n --arg m "$MODEL" --arg p "$PROMPT" --arg h "$hunks" \
    '{model: $m, max_tokens: 6000, temperature: 0,
      reasoning: {enabled: false},
      messages: [{role: "user", content: ($p + "\n\n" + $h)}]}')"

ask() {
    # 2>/dev/null: the first attempt may well answer 400 over reasoning, and
    # curl's own stderr line would read like a genuine failure. The error text
    # arrives in the body anyway and is inspected below.
    curl -sS --fail-with-body --max-time 600 2>/dev/null \
        https://openrouter.ai/api/v1/chat/completions \
        -H "Authorization: Bearer $OPENROUTER_API_KEY" \
        -H "Content-Type: application/json" \
        -d "$1"
}

resp="$(ask "$payload")" || {
    if printf '%s' "$resp" | grep -qi 'reasoning'; then
        resp="$(ask "$(printf '%s' "$payload" | jq 'del(.reasoning)')")" \
            || { echo "OpenRouter request failed: $resp" >&2; exit 1; }
    else
        echo "OpenRouter request failed: $resp" >&2; exit 1
    fi
}

text="$(printf '%s' "$resp" | jq -r '.choices[0].message.content // empty')"
[ -n "$text" ] || { echo "empty response: $resp" >&2; exit 1; }
cost="$(printf '%s' "$resp" | jq -r '.usage.cost // empty')"

# Only now, when everything worked, touch stdout.
echo
echo "### What the conflicts are about"
echo
echo "> Generated by \`$MODEL\`${cost:+ for \$$cost} from the conflict hunks alone."
echo "> A hint, not a document: the counts and file lists above are verifiable,"
echo "> this section is not."
echo
printf '%s\n' "$text"
if [ "$dropped" -gt 0 ]; then
    echo
    echo "_Another $dropped files did not fit the budget and were never shown to the model._"
fi
